[package]
name = "boom-cli"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cmd_lib = "1.1.0"
dirs = "3.0.2"
spinners = "2.0.0"
substring = "1.4.5"
